# syntax=docker/dockerfile:1
# Etapa de construccion
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
# Caché para acelerar la instalación de dependencias de desarrollo
RUN --mount=type=cache,target=/root/.npm \
    npm install
COPY . .
RUN npm run build

# Etapa de produccion
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]