# Se utiliza StatefulSet en lugar de Deployment porque los nodos de la base de datos
# necesitan una identidad única y persistente (nombre y disco propio).
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # Nombre del conjunto de pods, parametrizado desde values.yaml
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
spec:
  # El Service Headless permite que los pods se encuentren entre sí por DNS interno para formar el clúster.
  serviceName: {{ .Values.database.name }}-headless
  
  # Definimos las 2 réplicas para garantizar la disponibilidad.
  replicas: {{ .Values.database.replicas | default 2 }}
  
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
      
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: rqlite
        image: {{ .Values.database.image }}
        resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
        # Configurar rqlite para trabajar en red y persistir datos.
        args: 
          # Identificador único del nodo en el clúster Raft.
          - "-node-id"
          - "$(POD_NAME)"
          # Dirección donde el Backend enviará las consultas SQL.
          - "-http-addr"
          - "$(POD_IP):4001"
          # Dirección para la comunicación interna de sincronización entre pods.
          - "-raft-addr"
          - "$(POD_IP):4002"
          - "-disco-mode"
          - "dns"
          - "-disco-config"
          - '{"name":"{{ .Values.database.name }}-headless"}'
          # Directorio donde se guardará el archivo de base de datos replicado.
          - "/data"
          
        # 
        # obtenemos el nombre real del Pod (vuela-db-0, vuela-db-1) y se lo damos a rqlite.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
              
        # 4001 para la API (Backend) y 4002 para el consenso (Raft).
        ports:
        - containerPort: 4001
          name: http
        - containerPort: 4002
          name: raft
          
        # Conectamos el contenedor con el volumen persistente definido abajo.
        volumeMounts:
        - name: db-data
          mountPath: /data
   
  # Crea un disco físico independiente para cada una de las 2 réplicas.
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      # ReadWriteOnce significa que el disco está atado a un pod específico, 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          # Tamaño del almacenamiento definido en el archivo values.yaml.
          storage: {{ .Values.database.storageSize | default "1Gi" }}

---
# SERVICIO HEADLESS: Un tipo especial de servicio sin IP virtual.
# Permite que cada pod tenga su propio registro DNS.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}-headless
spec:
  clusterIP: None
  ports:
    - port: 4001
      name: http
    - port: 4002
      name: raft
  selector:
    app: {{ .Values.database.name }}