apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.name }}-sa
  labels:
    app: {{ .Values.backend.name }}
# Opcional: Evita que el token se monte automáticamente si la app no lo usa
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.name }}-sa
  labels:
    app: {{ .Values.frontend.name }}
automountServiceAccountToken: false